[project]
name = "camera-face-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mediapipe>=0.10.20",
    "opencv-python>=4.10.0.84",
    "pyvirtualcam>=0.12.0",
    "ultralytics>=8.3.55",
]
